# Generated by Django 2.2.11 on 2020-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True),
        ),
    ]
